## S14a: Lab 2 - Numpy

Below is quick quickstart with numpy, designed to give new users a sense of how the library works. There is so much more functionality, and developers have provided an incredible [tutorial](https://numpy.org/devdocs/user/quickstart.html) for anyone ready for a deeper dive.

Also for need X need guidance, take a look at the [reference](https://numpy.org/doc/1.18/reference/index.html).

### The basics: 1D and 2D arrays

In [136]:
# Import numpy
import numpy as np

In [137]:
!pip install numpy

In [138]:
# Build a one dimensional (1D) numpy array directly

numpy_1d = np.array([1, 2, 3])
numpy_1d

array([1, 2, 3])

In [139]:
# Take a look at 1D dimensionality

np.ndim(numpy_1d)

1

In [140]:
# Take a look at 1D shape - (length, 

np.shape(numpy_1d)

(3,)

In [141]:
# Grab values at certain positions in 1D

numpy_1d[0]

1

In [142]:
# Build a two dimensional (2D) numpy array - "array of arrays"

numpy_2d = np.array([[4, 5, 6], [7, 8, 9]])
numpy_2d

array([[4, 5, 6],
       [7, 8, 9]])

In [143]:
# Take a look at 2D dimensionality

np.ndim(numpy_2d)

2

In [144]:
# Take a look at a 2D shape - (#row, #col)
np.shape(numpy_2d)

(2, 3)

In [145]:
# !!!YOUR TURN!!!

# Grab values at certain positions in 2D

print(numpy_2d[1, 2])
print(numpy_2d[0, 2])
print(numpy_2d[1, 1])

9
6
8


In [146]:
# Slice out portions of the array

numpy_2d[1, 1:3]

array([8, 9])

In [147]:
# Grab with condition
numpy_2d[numpy_2d >= 6]

array([6, 7, 8, 9])

In [148]:
# Reshape your 3d array, reversing rows and cols

numpy_2d.reshape(3, 2)

array([[4, 5],
       [6, 7],
       [8, 9]])

### Building / transforming arrays - selections

In [149]:
# Build a numpy array using a range - (start at, up to, step size)

np.arange(3, 10, 3)

array([3, 6, 9])

In [150]:
# Build a numpy array using evenly spaced points in a range - (start at, up to, breakpoints)

np.linspace(3, 15, 5)

array([ 3.,  6.,  9., 12., 15.])

In [151]:
# Create 1D array of 0s

np.zeros(3)

array([0., 0., 0.])

In [152]:
# Create 2D arrayy of 1s

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [153]:
# !!!YOUR TURN!!!

# Create 2D array of random numbers
#
# you could just use numpy.random.choice with the argument replace=False, which ensures each element is not repeated:
randC = np.stack([np.random.choice(range(999), 10, replace=False) for i in range(10)])
randC


array([[660, 973, 331, 328, 135, 677, 611, 811, 803, 511],
       [240, 126, 441, 899,  12, 299, 251, 852, 978, 570],
       [417, 170,  15, 895, 506, 393, 700, 678, 383, 542],
       [400, 339, 794, 819, 953, 661, 998, 141, 438, 443],
       [262, 709, 256, 773, 924, 821, 873, 417, 844, 203],
       [506, 647, 266, 418, 172, 261,  78, 142,  55, 490],
       [214, 951, 783, 213,  28, 298, 303, 888, 952, 495],
       [ 16, 273, 871, 290,  60, 600, 317, 586, 176, 521],
       [613, 267, 697, 666, 828, 584, 743, 527, 669, 239],
       [697, 624, 740, 419, 796, 442, 652, 342, 349, 318]])

In [154]:
# Get min and max
[randC.min(), randC.max()]

[12, 998]

### Math, [ref.](https://numpy.org/doc/1.18/reference/routines.math.html)

In [156]:
# Multiplication / divide

print('*.', np.multiply(npx, npy))
print('/.', np.divide(npx, npy))


*. [[ 5. 12.]
 [21. 32.]]
/. [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [157]:
# And other nice Math functions

print('SQRT.', np.sqrt(npx))
print('Power.', np.power(npx, npy))
print('Negative.', np.negative(npx))

SQRT. [[1.         1.41421356]
 [1.73205081 2.        ]]
Power. [[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]
Negative. [[-1. -2.]
 [-3. -4.]]


In [167]:
# !!!YOUR TURN!!!

# Path attention to the second argument - the axis
print('1:', np.sqrt(npy))
print('2:', np.sqrt(npx))

1: [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
2: [[1.         1.41421356]
 [1.73205081 2.        ]]


In [155]:
# Addition / subtraction (you can define type)

npx = np.array([[1, 2], [3, 4]], dtype=np.float64)
npy = np.array([[5, 6], [7, 8]], dtype=np.float64)

print('+.', np.add(npx, npy))
print('-.', np.subtract(npx, npy))

+. [[ 6.  8.]
 [10. 12.]]
-. [[-4. -4.]
 [-4. -4.]]


In [159]:
# Broadcasting - when performing mathematical operations, shape matters

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(len(x)):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [160]:
# Copying - if you need your changes not to effect the original array, make a copy
y_copy = y.copy()
y_copy[0][0:] = -9999
print(y)
print(y_copy)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[-9999 -9999 -9999]
 [    5     5     7]
 [    8     8    10]
 [   11    11    13]]


In [161]:
# !!!YOUR TURN!!!

# Path attention to the second argument - the axis



In [162]:
# Broadcasting - when performing mathematical operations, shape matters

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

 

In [163]:
# Copying - if you need your changes not to effect the original array, make a copy
y_copy = y.copy()
y_copy[0][0:] = -9999
print(y)
print(y_copy)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-9999 -9999 -9999]
 [    4     5     6]
 [    7     8     9]
 [   10    11    12]]
